ALTER TYPE "EmailNotificationType" ADD VALUE IF NOT EXISTS 'AUTH_OTP';
ALTER TYPE "EmailNotificationType" ADD VALUE IF NOT EXISTS 'AUTH_RECOVERY';
ALTER TYPE "EmailNotificationType" ADD VALUE IF NOT EXISTS 'ONBOARDING_WELCOME';
ALTER TYPE "EmailNotificationType" ADD VALUE IF NOT EXISTS 'ONBOARDING_GUIDE';
