services:
  localstack:
    image: localstack/localstack:latest
    container_name: trustloop-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:16-alpine
    container_name: trustloop-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trustloop
    volumes:
      - trustloop-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: trustloop-redis
    ports:
      - "6379:6379"

volumes:
  trustloop-postgres-data:
