ALTER TABLE "WorkspaceQuota"
ADD COLUMN IF NOT EXISTS "onCallRotationEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "onCallRotationIntervalHours" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN IF NOT EXISTS "onCallRotationAnchorAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
